apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-detector.fullname" . }}
  labels:
    app: {{ include "fraud-detector.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    app: {{ include "fraud-detector.name" . }}

